// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFD0-smkuCymonZAWjcmfl0voezd4VC8',
    appId: '1:995843540829:web:35dc31d1582291512d4ab4',
    messagingSenderId: '995843540829',
    projectId: 'testflutter-cff8e',
    authDomain: 'testflutter-cff8e.firebaseapp.com',
    storageBucket: 'testflutter-cff8e.appspot.com',
    measurementId: 'G-XQL009G45N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw00lcxQdTI8OZ8RaAl1nniaZGhKY5aHI',
    appId: '1:995843540829:android:c4f04bb519b460e02d4ab4',
    messagingSenderId: '995843540829',
    projectId: 'testflutter-cff8e',
    storageBucket: 'testflutter-cff8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-6-fjZ3xQe1eJ8KxLyr-nOpGGzZkSa4',
    appId: '1:995843540829:ios:7fbd4733824fc8942d4ab4',
    messagingSenderId: '995843540829',
    projectId: 'testflutter-cff8e',
    storageBucket: 'testflutter-cff8e.appspot.com',
    iosClientId: '995843540829-11b7ercm9nvtirqjfq3bi4edboh2l63i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-6-fjZ3xQe1eJ8KxLyr-nOpGGzZkSa4',
    appId: '1:995843540829:ios:96a4ff9f484ea3972d4ab4',
    messagingSenderId: '995843540829',
    projectId: 'testflutter-cff8e',
    storageBucket: 'testflutter-cff8e.appspot.com',
    iosClientId: '995843540829-032hqv8vb05ms8mt3ms3dv5autnar7fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
